[versions]
# Used in [/gradle/build-config/src/main/kotlin/PluginKotlinMultiplatform.kt]
android-sdk-min = "26"
android-sdk-compile = "36"
android-sdk-target = "36"
android-ndk = "27.0.12077973"
java = "17"

[plugins]
android-application = { id = "hikari.plugins.android.application" }
android-base = { id = "hikari.plugins.android.base" }
android-library = { id = "hikari.plugins.android.library" }
android-test = { id = "hikari.plugins.android.test" }
compose = { id = "hikari.plugins.compose.android" }
kotlin-multiplatform = { id = "hikari.plugins.kotlin.multiplatform" }
spotless = { id = "hikari.plugins.spotless" }
